### ISSUE TITLE
Error when patching

### ISSUE THREAD

**Issue by killy67000** [kiooeht/Hubris#22]
I'm getting the following error when i try to start the game with this mod:

Patch Class: [com.evacipated.cardcrawl.mod.hubris.patches.TheBottlerPatch]
 - Patching [com.megacrit.cardcrawl.dungeons.AbstractDungeon.getEvent()]
 - Adding Insert @ 2483...

{
com.evacipated.cardcrawl.mod.hubris.patches.TheBottlerPatch.Insert($$, tmp);
}
com.evacipated.cardcrawl.modthespire.patcher.PatchingException: javassist.CannotCompileException: [source error] Insert(java.util.ArrayList) not found in com.evacipated.cardcrawl.mod.hubris.patches.TheBottlerPatch
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:209)
	at com.evacipated.cardcrawl.modthespire.Patcher.finalizePatches(Patcher.java:150)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:199)
	at com.evacipated.cardcrawl.modthespire.ui.ModSelectWindow.lambda$null$1(ModSelectWindow.java:272)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javassist.CannotCompileException: [source error] Insert(java.util.ArrayList) not found in com.evacipated.cardcrawl.mod.hubris.patches.TheBottlerPatch
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:183)
	at com.evacipated.cardcrawl.modthespire.patcher.InsertPatchInfo.doPatch(InsertPatchInfo.java:207)
	... 4 more
Caused by: compile error: Insert(java.util.ArrayList) not found in com.evacipated.cardcrawl.mod.hubris.patches.TheBottlerPatch
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:749)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

This happens with just BaseMod, StSLib and Hubris enabled.

**Comment by kiooeht** [comment]
You need to update to the latest version of Hubris.
