### ISSUE TITLE
Potential Issue with Xylophone patch

### ISSUE THREAD

**Issue by STSsadoni** [kiooeht/Hubris#32]
I'm getting this crash whenever I play the Fan of Knives card from RatMod.  Don't know if it's your problem or RatMod's, but I'll post it here for you to look at.

Exception: java.lang.NullPointerException
05:24:52.599 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:24) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.common.DamageAllEnemiesAction.<init>(DamageAllEnemiesAction.java:37) ~[desktop-1.0.jar:?]
	at ratmod.cards.FanOfKnives.use(FanOfKnives.java:51) ~[RatMod.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:159) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:283) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2531) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:883) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:435) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]

**Comment by kiooeht** [comment]
ZylopatchPatch just appears in the crash log because it's a part of every card being played.
I think I tracked down why the crash happens (though I couldn't get it to happen) and believe it's RatMod's fault. I'll comment on your issue on RatMod for how I think they can fix it.
