### ISSUE TITLE
Crash when trying to summon Fox Familiar while having Goblin ally

### ISSUE THREAD

**Issue by AvangionQ** [kiooeht/Hubris#41]
Crash when trying to summon Fox Familiar while having Goblin ally

Exception: java.lang.NullPointerException
00:27:11.919 ERROR core.CardCrawlGame> Exception caught
java.lang.NullPointerException: null
	at mysticmod.cards.SummonFamiliar.use(SummonFamiliar.java:57) ~[TheMystic.jar:?]
	at com.evacipated.cardcrawl.mod.hubris.patches.ZylophonePatch$MultiUse.use(ZylophonePatch.java:51) ~[Hubris.jar:?]
	at com.megacrit.cardcrawl.characters.AbstractPlayer.useCard(AbstractPlayer.java:1594) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:297) ~[?:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:151) ~[?:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:279) ~[?:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2554) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:878) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:429) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Controllers: removed manager for application, 0 managers active
Game closed.

**Comment by kiooeht** [comment]
This crash doesn't have to do with Hubris.
Report it to Mystic (Fox Familiar) (https://github.com/JohnnyDevo/The-Mystic-Project) and Replay (Goblin ally) (https://github.com/The-Evil-Pickle/Replay-the-Spire/issues) instead.
